### ISSUE TITLE
This link is broken

### ISSUE THREAD

**Issue by 4riful** [riramar/Web-Attack-Cheat-Sheet#7]
https://appsecco.com/books/subdomain-enumeration

Can you please have a check out sir ? This link is broken

**Comment by riramar** [comment]
Yeap... it seems they removed the page. I've replaced with the latest version of Wayback Machine (https://web.archive.org/web/20211127183642/https://appsecco.com/books/subdomain-enumeration/).
Thanks for reporting that! :)
